myset: myset.o set.o
	gcc -g -Wall -ansi -pedantic myset.o set.o -o mysetProg.o

myset.o: myset.c
	gcc -c -Wall -ansi -pedantic myset.c -o myset.o

set.o: set.c
	gcc -c -Wall -ansi -pedantic set.c -o set.o



